### ISSUE TITLE
Error on line number which doesn't exists

### ISSUE THREAD

**Issue by anil4u-04** [limitusus/json-syntax-check#18]
Hey,

it is giving an error at line number which doesn't even exists

```
Files below has/have JSON syntax error (of 2 files)
- /github/workspace/myfile.json: 451: unexpected token at '{' ...

```
But the file has only 314 lines.

this is my action file

```
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        uses: limitusus/json-syntax-check@v2
        with:
          patterns: "\\.json$"    
```

Do we need to add paths also..? 

```
    paths:
      - '**.json'
```

Please help me . Thanks
