### ISSUE TITLE
Seems not working as intended

### ISSUE THREAD

**Issue by dgw** [limitusus/json-syntax-check#4]
I'm trying to set this up on one of my repos, and was very confused when my first test push with an _intentional_ JSON error did not fail the check.

Then I looked at the log and saw "(of 0 files)". That's weird, because my project definitely has at least one file with the `.json` extension. And it should have failed the check, but the run passed.

Turns out the [test](https://github.com/limitusus/json-syntax-check/runs/1322186301#step:4:5) [runs](https://github.com/limitusus/json-syntax-check/runs/1322199452#step:4:5) on this very repo also say "(of 0 files)". Is using `/data/` as the `BASE` intended? GitHub checks out the repo to `/github/workspace` on the Actions runner. I don't think anything goes in `/data/`.

Notably, overriding `BASE` so it _would_ point at the repo in my next debugging run (`BASE: /github/workspace` in the step's `env:` block) led to this action trying to lint every file in the repo—and I was in fact using the suggested pattern `\\.json$`. Of course, the files in `.git` and so on are _not_ valid JSON, but why is the action even checking them?

I'll include my current workflow file below. Either I'm completely misunderstanding how this action is supposed to work, or it doesn't function as documented. 😕

```yml
name: JSON check

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        env:
          BASE: /github/workspace
        with:
          pattern: "\\.json$"
```
